apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: web-tier-np 
  namespace: policygen
spec:
  podSelector:
    matchLabels:
      appl: hrapp
      tier: web
  policyTypes:
  egress:
  - to:
    - podSelector:
        matchLabels:
          appl: hrapp
          tier: app
