apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: db-tier-np 
  namespace: policygen
spec:
  podSelector:
    matchLabels:
      appl: hrapp
      tier: db
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          appl: hrapp
          tier: app

