apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: cn2-policy-generator-v3
  namespace: argo
spec:
  serviceAccountName: argo-ops-admin
  entrypoint: cn2-report-dag
  templates:
  - name: fetch-nw-policy-tpl
    inputs:
      parameters:
        - name: fw_input
    script:
      image: svl-artifactory.juniper.net/atom-docker-remote/python:alpine3.6
      command: [python]
      source: |
        import time
        print('--Fetch current NW policy-- {{inputs.parameters.fw_input}}')
        retry_max = 5
        retry_cnt = 0
        while retry_cnt < retry_max:
          time.sleep(1)
          retry_cnt += 1
          print('processing')
        print('Completed')
  - name: fetch-analytics-tpl
    script:
      image: svl-artifactory.juniper.net/atom-docker-remote/python:alpine3.6
      command: [python]
      source: |
        import time
        print('--Fetch Analytics info--')
        retry_max = 5
        retry_cnt = 0
        while retry_cnt < retry_max:
          time.sleep(1)
          retry_cnt += 1
          print('processing')
        print('Completed')
  - name: run-analysis-tpl
    inputs:
      parameters:
        - name: fw_input      
      artifacts:
      - name: pyrunner
        path: /usr/local/src/cn2_py_runner.py
        mode: 0755
        http:
          url: https://raw.githubusercontent.com/roshpr/argotest/main/cn2-experiments/cn2_py_runner.py 
    script:
      image: svl-artifactory.juniper.net/atom-docker-remote/python:alpine3.6
      command: [python]
      args: ["/usr/local/src/cn2_py_runner.py", "{{inputs.parameters.fw_input}}"]
  - name: report-policy-findings-tpl
    inputs:
      parameters:
        - name: fw_input      
      artifacts:
      - name: nwpolicy1
        path: /usr/local/src/nw-policy1.yaml
        mode: 0755
        http:
          url: https://raw.githubusercontent.com/roshpr/argotest/main/cn2-experiments/nw-policy1.yaml
      - name: nwpolicy2
        path: /usr/local/src/nw-policy2.yaml
        mode: 0755
        http:
          url: https://raw.githubusercontent.com/roshpr/argotest/main/cn2-experiments/nw-policy2.yaml
      - name: nwpolicy3
        path: /usr/local/src/nw-policy3.yaml
        mode: 0755
        http:
          url: https://raw.githubusercontent.com/roshpr/argotest/main/cn2-experiments/nw-policy3.yaml          
    script:
      image: svl-artifactory.juniper.net/atom-docker-remote/bash
      command: [bash]
      source: |
        echo "Generated network policies"
        echo "==========================="
        echo "Network policy 1"
        cat /usr/local/src/nw-policy1.yaml
        echo "==========================="
        echo "Network policy 2"
        cat /usr/local/src/nw-policy2.yaml        
        echo "==========================="
        echo "Network policy 3"
        cat /usr/local/src/nw-policy3.yaml  
        echo "==========================="    
  - name: push-configs-git-repo-tpl
    inputs:
      parameters:
        - name: fw_input      
      artifacts:
      - name: nwpolicy1
        path: /usr/local/src/nw-policy1.yaml
        mode: 0755
        http:
          url: https://raw.githubusercontent.com/roshpr/argotest/main/cn2-experiments/nw-policy1.yaml
      - name: nwpolicy2
        path: /usr/local/src/nw-policy2.yaml
        mode: 0755
        http:
          url: https://raw.githubusercontent.com/roshpr/argotest/main/cn2-experiments/nw-policy2.yaml
      - name: nwpolicy3
        path: /usr/local/src/nw-policy3.yaml
        mode: 0755
        http:
          url: https://raw.githubusercontent.com/roshpr/argotest/main/cn2-experiments/nw-policy3.yaml          
    script:
      image: svl-artifactory.juniper.net/atom-docker/atom-of/jdeployer/ubuntugitcli
      command: [bash]
      source: |
        echo "Push network policies to git repo for syncing"
        git clone http://git-server.argocd.svc.cluster.local/git/jdeploy.git
        cd jdeploy
        mkdir -p cn2experiments
        cd cn2experiments
        cp /usr/local/src/nw-policy1.yaml .
        cp /usr/local/src/nw-policy2.yaml .
        cp /usr/local/src/nw-policy3.yaml .
        git config --global user.email "automation@cn2.net"
        git config --global user.name "CN2 Automation"
        git add .
        git commit -m '`date`: add cn2 policies'
        git push origin master
        
  - name: cn2-report-dag
    inputs:
      parameters:
        - name: fw_application  
        - name: process_time_period 
    dag:
      tasks:
      - name: turn-off-firewall
        template: fetch-nw-policy-tpl 
        arguments:
          parameters:
            - name: fw_input
              value: "{{inputs.parameters.fw_application}}"        
      - name: fetch-current-nw-policy
        template: fetch-nw-policy-tpl 
        dependencies: [turn-off-firewall]
        arguments:
          parameters:
            - name: fw_input
              value: "{{inputs.parameters.fw_application}}"

      - name: fetch-analytics-info
        dependencies: [fetch-current-nw-policy]
        template: fetch-analytics-tpl   

      - name: run-analysis-create-nw-policy-app1
        dependencies: [fetch-analytics-info]
        template: run-analysis-tpl
        arguments:
          parameters:
            - name: fw_input
              value: "{{inputs.parameters.fw_application}}"  

      - name: run-analysis-create-nw-policy-app2
        dependencies: [fetch-analytics-info]
        template: run-analysis-tpl
        arguments:
          parameters:
            - name: fw_input
              value: "{{inputs.parameters.fw_application}}"
      - name: run-analysis-create-nw-policy-app3
        dependencies: [fetch-analytics-info]
        template: run-analysis-tpl
        arguments:
          parameters:
            - name: fw_input
              value: "{{inputs.parameters.fw_application}}"
      - name: run-analysis-create-nw-policy-app4
        dependencies: [fetch-analytics-info]
        template: run-analysis-tpl
        arguments:
          parameters:
            - name: fw_input
              value: "{{inputs.parameters.fw_application}}"              
      - name: report-policy-findings
        dependencies: [run-analysis-create-nw-policy-app1,run-analysis-create-nw-policy-app2,run-analysis-create-nw-policy-app3,run-analysis-create-nw-policy-app4]
        template: report-policy-findings-tpl
        arguments:
          parameters:
            - name: fw_input
              value: "{{inputs.parameters.fw_application}}"

      - name: push-configs-git-repo
        dependencies: [report-policy-findings]
        template: push-configs-git-repo-tpl
        arguments:
          parameters:
            - name: fw_input
              value: "{{inputs.parameters.fw_application}}"
              
      - name: turn-on-firewall
        dependencies: [report-policy-findings]
        template: fetch-nw-policy-tpl 
        arguments:
          parameters:
            - name: fw_input
              value: "{{inputs.parameters.fw_application}}"  

