apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cn2deploy2-analytics
spec:
  destination:
    name: ''
    namespace: ''
    server: 'https://172.31.19.49:33335'
  source:
    path: ''
    repoURL: 'https://hub.jnprlabs.net/chartrepo/contrail'
    targetRevision: 0.1.0-rev60b6ae081
    chart: contrail-analytics
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - Validate=false
      - CreateNamespace=true
