apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: application-set-infra
spec:
  generators:
  - list:
      items:
      - cluster: default
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: 'infra'
    spec:
      project: default
      source:
        repoURL: https://github.com/roshpr/argotest
        targetRevision: HEAD
        path: infra
      destination:
        server: https://kubernetes.default.svc
        namespace: default
