apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: orch-sync-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: '1'
    argocd.argoproj.io/hook: 'Sync'  
spec:
  destination:
    namespace: default
    name: in-cluster
  project: default
  source:
    path: orch-sync
    repoURL: https://github.com/roshpr/argotest
    targetRevision: HEAD
