apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sitea-cluster1-cni
  namespace: argocd
  labels:
    tag: deployment
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: 'https://172.31.19.49:33311'
    namespace: default
  project: default
  source:
    repoURL: 'https://github.com/roshpr/argotest'
    path: cn2apps/cnis
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
