apiVersion: batch/v1
kind: Job
metadata:
  name: startup
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "1"
spec:
  template:
    spec:
      containers:
        - name: startup-sql-schema
          image: alpine:latest
          command: ["sleep", "5"]
      restartPolicy: Never  
