apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx2-pv1
  annotations:
    argocd.argoproj.io/sync-wave: "5"  
    argocd.argoproj.io/hook: Sync    
#    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /mnt/app2
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/os
          operator: In
          values:
          - linux
