apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx5
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"  
spec:
  destination:
    namespace: app-nginx5
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated:
      selfHeal: true  
    syncOptions:
      - CreateNamespace=true
  source:
    chart: nginx
    helm:
      parameters:
      - name: replicaCount
        value: "2"
      - name: service.httpsPort
        value: "8443"
      - name: service.type
        value: NodePort
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 8.5.3
