apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-memcache
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"  
spec:
  project: default
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: '*'
    helm:
      parameters:
        - name: persistence.size
      value: 1Gi
    chart: memcached
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: memcache
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
