apiVersion: batch/v1
kind: Job
metadata:
  name: middle
  annotations:
    argocd.argoproj.io/sync-wave: "5"  
    argocd.argoproj.io/hook: PostSync    
spec:
  template:
    spec:
      containers:
      - name: sleep
        image: alpine:latest
        command: ["echo", "post-sync"]
      restartPolicy: Never
  backoffLimit: 0
