---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    name: argo-ops-admin
  name: argo-ops-admin
rules:
  - apiGroups: ['*']
    resources: ['*']
    verbs: ['*']
  - nonResourceURLs: ['*']
    verbs: ['*']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    name: argo-ops-admin
  name: argo-ops-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-ops-admin
subjects:
  - kind: ServiceAccount
    name: argo-ops-admin
    namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    name: argo-ops-admin
  name: argo-ops-admin
  namespace: default
