apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cn2-k8cluster2
  namespace: argocd
  labels:
    tag: deployment
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: 'https://172.31.19.49:33338'
    namespace: default
  project: default
  source:
    repoURL: 'https://github.com/roshpr/argotest'
    path: cn2deploy
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

