apiVersion: v1
kind: Secret
metadata:
  name: cn2-staging
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
    tag: clusters
type: Opaque
stringData:
  name: cn2-staging
  server: https://172.31.19.49:33336
  config: |
    {
      "bearerToken": "eyJhbGciOiJSUzI1NiIsImtpZCI6InlMVTVab3pPRk5kaUd0dTdtTGpOSXVQZG9iTnNMekREeTh1c0FpZGhnTU0ifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImFyZ28tb3BzLWFkbWluLXRva2VuLTV4aGxjIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6ImFyZ28tb3BzLWFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiMGEwMmE4YzYtYTg5Yi00OGEzLWE4ODItZDEyNzI2Mjk4ODcxIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OmRlZmF1bHQ6YXJnby1vcHMtYWRtaW4ifQ.sLr8bYrJg5QGLwm49VV1uqQy1uYM0dlmkKOupmBpBw55PE6YQ1qGd99HLLItjb0QCs_56O3zmcdQ0HJZGez2TJya6SoYyjZXUmd8scFp1_XfAueX9HiU7_cZ180hvxGYpcA4XBAldlCJ6XIhh6a7nNbOjM1oWhtzCLjGaIBl8CIgyRGIY0zUT9-1FmsBP29UA7gb1TXoCFJk3KPT7mQSOfLg71DCZ1OpiFQOpYTq7vjj-KslLezIzbl6ZEs_O0AESe_SR-6ufXeGMflF584lRAziRre65dTUzOtpOqb_4h0b8wVC6cAGfS6PHRabMQgDwd998F1V0zgVD09bW5lW7Q",
      "tlsClientConfig": {
        "insecure":true
      }
    }
